engines:
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
  duplication:
    enabled: true
      config:
        languages:
        - PHP
        - javascript
  csslint:
    enabled: true
  fixme:
    enabled: true
  scss-lint:
    enabled: true
exclude_paths:
- "webd/includes/bootstrap-3.3.5-dist/**/*"
- "webd/includes/jquery/**/*"
- "webd/includes/charts/**/*"
