engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  phpcodesniffer:
    enabled: true
  duplication:
    enabled: true
  csslint:
    enabled: true
  phpmd:
    enabled: true
  fixme:
    enabled: true
  scss-lint:
    enabled: true
exclude_paths:
- "webd/includes/bootstrap-3.3.5-dist/**/*"
- "webd/includes/jquery/**/*"
- "webd/includes/charts/**/*"
